version: '3.7'
services:

  database:
    image: mysql:latest
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: M@tink14901490
      MYSQL_DATABASE: yamchi_db
    networks:
      dbn:
        aliases:
          - database
    volumes:
      - mysql:/var/lib/mysql
  backend:
    build:
      context: ./backend
    ports:
      - '3001:3000'
    volumes:
      - backend:/backend
    restart: on-failure
    links:
      - database
    networks:
      db_network:
        aliases:
          - back
    environment:
      - DATABASE_URL=postgresql://postgres:M@tink14901490@87.107.165.83:5432/Nimkatiha
  frontend:
    build:
      context: ./frontend
    ports:
      - '8000:8080'
    volumes:
      - frontend:/frontend
    environment:
      - VUE_APP_SERVER_ADDRESS=http://api.nimkatiha.com
  enduser:
    build:
      context: ./enduser
    ports:
      - '8001:8080'
    volumes:
      - enduser:/enduser
    environment:
      - VUE_APP_SERVER_ADDRESS=http://api.nimkatiha.com
networks:
  db_network:
    driver: bridge
volumes:
  mysql:
  backend:
  frontend:
  database: